### ISSUE TITLE
Define a solution how we should handle private key files in docker containers, used by CodeRepo and Exec

### ISSUE THREAD

**Issue by mattiasrunge** [Combitech/codefarm#10]

**Comment by christensson** [comment]
From commit e8669558ef92af91b7423881021bc2123f061e57, the following is done when starting services using docker-compose:
- *mgmt* mounts directory `src/scripts/jwtKeys` at `/home/farmer/.ssh`
- *exec* mounts directory `src/scripts/execKeys` at `/home/farmer/execKeys`
- *coderepo* mounts directory `src/scripts/codeKeys` at `/home/farmer/codeKeys`
