### ISSUE TITLE
Define a solution how we store things peristantly in docker on docker-external paths, needed by MongoDB, RabbitMQ, Gerrit, ArtifactRepo, LogRepo, CodeRepo, UI

### ISSUE THREAD

**Issue by mattiasrunge** [Combitech/codefarm#11]

**Comment by christensson** [comment]
List configured volumes for all services:
```bash
docker-compose config --services|sed 's/\(.*\)/scripts_\1_1/'|xargs docker inspect --format '{{json .Config.Volumes}}'
```

When run using docker-compose using configuration src/scripts/docker-compose.yml 
- [MongoDB container](https://hub.docker.com/_/mongo/) by default stores data in two data-volumes mounted at `/data/db' and '/data/configdb`.
- [RabbitMQ container](https://hub.docker.com/_/rabbitmq/)  by default stores data in data-volume mounted at `/var/lib/rabbitmq`
- *artifactrepo* mounts data-volume `artifactvolume` at `/home/farmer/data`
- *logrepo* mounts data-volume `logvolume` at `/home/farmer/data`
