### ISSUE TITLE
Define and create the ability to use Windows machines as Exec slaves

### ISSUE THREAD

**Issue by mattiasrunge** [Combitech/codefarm#16]
SSH? Upload nodejs binary

**Comment by christensson** [comment]
Windows slave:
- nodejs install of v7.7.3
- Win32-OpenSSH install

**Comment by christensson** [comment]
Slave requirement:
- nodejs
- Cygwin + OpenSSH, see [howto](http://www.noah.org/ssh/cygwin-sshd.html)

Slave config:
- Add public key to /home/USER/.ssh/authorized_keys
- Set URI for slave to ssh://HOST:PORT/WINDOWS_PATH where WINDOWS_PATH is a windows-style path similar to c:\Users\User\someDir or c:/Users/User/someDir
