### ISSUE TITLE
Cleanup exec slave private key and user handling

### ISSUE THREAD

**Issue by christensson** [Combitech/codefarm#267]
Currently both *exec.slave* and *exec.backend* stores private keys.

A number of options exist:
- Set both *user* and *private key path* in *backend*. Do not set them in *slave*.
- Set both *user* and *private key path* in *slave*. Do not set them in *backend*.

**Comment by christensson** [comment]
@patrikfirek ping

**Comment by patrikfirek** [comment]
Har den i min TODO
