### ISSUE TITLE
gitlab coderepo backend

### ISSUE THREAD

**Issue by christensson** [Combitech/codefarm#282]
We in my team will start using gitlab. Our aim is to setup and use codefarm for our development. Please prepare with gitlab backend to make it as smooth as possible.

**Comment by patrikfirek** [comment]
Any more details about how you use gitlab, which commands should be supported?

**Comment by christensson** [comment]
Would be nice if gitlab "merge requests" were merged by some functional user, or even better of by some CI user. Seems to be support for that similar to that in GitHub. Start with the easiest first and then improve.
