### ISSUE TITLE
Test Status as Backend

### ISSUE THREAD

**Issue by patrikfirek** [Combitech/codefarm#296]
* Keep exec.job and let it represent a queued or executed job 
* Move script from flowctrl.step to exec.jobspec
* Add backend to Exec that connects to message bus

**Comment by patrikfirek** [comment]
Need to connect the steps and derviedby over different types with tags

**Comment by christensson** [comment]
The current solution creates exec.job via exec.jobspec when flowctrl.step is triggered (by baselinegen.baseline creation). The job status (started/finished) is set depending from backend.
